# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20140828_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='slug',
        ),
    ]
