# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_player_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
