# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20160204_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview_url',
            field=models.URLField(blank=True, help_text='A link to the preview image. Try http://vidthumb.com or http://embed.ly/embed.'),
        ),
    ]
