# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='body',
            field=models.TextField(blank=True, help_text='HTML'),
        ),
    ]
