# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20160328_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-priority', '-date']},
        ),
        migrations.AddField(
            model_name='release',
            name='priority',
            field=models.PositiveIntegerField(blank=True, help_text='Site-wide sort order (higher numbers first)', null=True),
        ),
    ]
