# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20160704_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='priority',
            field=models.PositiveIntegerField(blank=True, help_text='Site-wide sort order (higher numbers first)', null=True),
        ),
    ]
