# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_video_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-priority', 'publish', '-publish_on']},
        ),
    ]
