# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20141101_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, help_text='HTML'),
        ),
    ]
